### ISSUE TITLE
Theme cannot be imported

### ISSUE THREAD

**Issue by YoavRheims** [tunguskha/my-awesome-list#3]
Importing the theme to Stackbit failed because of missing required build command:

validating stackbit.yaml fields
[buildCommand] "buildCommand" is required
[publishDir] "publishDir" is required
[pagesDir] "pagesDir" is required

Screenshot:

![image](https://user-images.githubusercontent.com/4377522/66997897-f75bbf80-f0db-11e9-825b-9b12096cd69d.png)

**Comment by tunguskha** [comment]
Hi!
Thank you for reporting this issue.
It should work again!

**Comment by YoavRheims** [comment]
Merci :)
